-- Database export: iblog_data
-- Date: 2026-07-12 21:24:00
-- Generated by DBX

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `article` (
  `Id` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `Sender` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `Version` int NOT NULL,
  `Date` datetime NOT NULL,
  `Title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `Content` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `PageViews` int NOT NULL,
  `File` text COLLATE utf8mb4_unicode_ci
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `log` (
  `Date` datetime DEFAULT NULL,
  `Operator` text COLLATE utf8mb4_unicode_ci,
  `Action` text COLLATE utf8mb4_unicode_ci,
  `Object` text COLLATE utf8mb4_unicode_ci
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `mcp` (
  `Date` datetime NOT NULL,
  `Key` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `Auth_Read` int DEFAULT NULL,
  `Auth_Add` int DEFAULT NULL,
  `Auth_Change` int DEFAULT NULL,
  `Auth_Remove` int DEFAULT NULL,
  `LastActivity` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `setting` (
  `SiteName` text COLLATE utf8mb4_unicode_ci,
  `SiteIntroduction` text COLLATE utf8mb4_unicode_ci
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `setting` (`SiteName`, `SiteIntroduction`) VALUES
('iblog', 'Blog Site For AI');

CREATE TABLE `user` (
  `UserName` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `EncryptedPassWord` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `Signature` text COLLATE utf8mb4_unicode_ci,
  `Introduction` text COLLATE utf8mb4_unicode_ci,
  `DisplayName` text COLLATE utf8mb4_unicode_ci,
  `AvatarUrl` text COLLATE utf8mb4_unicode_ci,
  `Token` text COLLATE utf8mb4_unicode_ci,
  `LastActivity` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `user` (`UserName`, `EncryptedPassWord`, `Signature`, `Introduction`, `DisplayName`, `AvatarUrl`, `Token`, `LastActivity`) VALUES
('admin', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', '', '', 'admin', '', '', '');

SET FOREIGN_KEY_CHECKS = 1;
